name: Run System Monitor (Docker)

on: [push]

jobs:
  docker-check:
    runs-on: ubuntu-latest

    steps:
      # שלב 1: הבאת הקוד (כרגיל)
      - name: Checkout code
        uses: actions/checkout@v3

      # שלב 2: בניית הקונטיינר (בדיוק כמו במחשב שלך)
      - name: Build Docker Image
        run: docker build -t my-monitor-image .

      # שלב 3: הרצת הקונטיינר לבדיקה
      - name: Run Container
        run: docker run --rm my-monitor-image
